# Generated by Django 2.2.17 on 2020-11-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
