# Generated by Django 2.2.17 on 2020-11-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_class_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
